In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler
from scipy import stats
import warnings
import missingno as msno
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
warnings.filterwarnings('ignore')
%matplotlib inline

In [3]:
df=pd.read_csv('aftercleaning.csv')

In [5]:
df.head()

,Job Title,Job Description,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,Average slary,Min slary,Max slary,age,python,R,power bi
0,"Sr. Manager, Data Science - Fraud & ML Platform",Overview:\nABOUT OPORTUN\n\nOportun is a missi...,4.2,Oportun Inc,"San Carlos, CA",3000,2005,Company - Public,Lending,Finance,Unknown / Non-Applicable,169.0,130,208,15,1,1,1
1,Data Science Manager,Come join a growing financial technology compa...,4.1,"Continental Finance Company, LLC","Wilmington, DE",125,2005,Company - Private,Lending,Finance,Unknown / Non-Applicable,120.0,89,151,15,1,1,1
2,Operations Data Analyst,Make your mark. With more than $17.2 billion o...,3.8,Plante Moran,"Kalamazoo, MI",3000,1924,Company - Private,Accounting,Accounting & Legal,$500 million to $1 billion (USD),49.0,36,62,96,0,1,1
3,Data Analyst,"Overview:\nAt Grow Financial, we believe in se...",3.6,Grow Financial,"Brandon, FL",750,1955,Nonprofit Organization,Banks & Credit Unions,Finance,$50 to $100 million (USD),48.5,35,62,65,1,1,1
4,Data Scientist,What you’ll be doing...\nBe a part of the team...,3.9,Verizon,"Ashburn, VA",15000,2000,Company - Public,Telecommunications Services,Telecommunications,$10+ billion (USD),108.0,83,133,20,1,1,1

### choozsing relevent column
### get dummmy data
### train test split
### choosing modul

In [7]:
df.columns

Index(['Job Title', 'Job Description', 'Rating', 'Company Name', 'Location',
       'Size', 'Founded', 'Type of ownership', 'Industry', 'Sector', 'Revenue',
       'Average slary', 'Min slary', 'Max slary', 'age', 'python', 'R',
       'power bi'],
      dtype='object')

In [9]:
df_module=df[['Rating','Size','age','Industry','Sector','Revenue','Type of ownership','python','Average slary']]

In [10]:
df_module

,Rating,Size,age,Industry,Sector,Revenue,Type of ownership,python,Average slary
0,4.2,3000,15,Lending,Finance,Unknown / Non-Applicable,Company - Public,1,169.0
1,4.1,125,15,Lending,Finance,Unknown / Non-Applicable,Company - Private,1,120.0
2,3.8,3000,96,Accounting,Accounting & Legal,$500 million to $1 billion (USD),Company - Private,0,49.0
3,3.6,750,65,Banks & Credit Unions,Finance,$50 to $100 million (USD),Nonprofit Organization,1,48.5
4,3.9,15000,20,Telecommunications Services,Telecommunications,$10+ billion (USD),Company - Public,1,108.0
...,...,...,...,...,...,...,...,...,...
86,4.2,350,21,Staffing & Outsourcing,Business Services,$100 to $500 million (USD),Subsidiary or Business Segment,1,110.0
87,-1.0,0,0,-1,-1,-1,-1,0,110.0
88,5.0,125,6,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,Company - Private,0,110.0
89,4.8,125,9,Internet,Information Technology,$25 to $50 million (USD),Company - Private,0,110.0
90,-1.0,0,0,-1,-1,-1,-1,0,110.0

In [11]:
df_dum=pd.get_dummies(df_module)

In [12]:
df_dum

,Rating,Size,age,python,Average slary,Industry_-1,Industry_Accounting,Industry_Advertising & Marketing,Industry_Aerospace & Defense,Industry_Architectural & Engineering Services,...,Revenue_-1,Revenue_Less than $1 million (USD),Revenue_Unknown / Non-Applicable,Type of ownership_-1,Type of ownership_Company - Private,Type of ownership_Company - Public,Type of ownership_Contract,Type of ownership_Hospital,Type of ownership_Nonprofit Organization,Type of ownership_Subsidiary or Business Segment
0,4.2,3000,15,1,169.0,0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0
1,4.1,125,15,1,120.0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
2,3.8,3000,96,0,49.0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,3.6,750,65,1,48.5,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,3.9,15000,20,1,108.0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,4.2,350,21,1,110.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
87,-1.0,0,0,0,110.0,1,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
88,5.0,125,6,0,110.0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
89,4.8,125,9,0,110.0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
90,-1.0,0,0,0,110.0,1,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0

In [15]:
# train test split
from sklearn.model_selection import train_test_split
X=df_dum.drop('Average slary',axis=1)
y=df_dum['Average slary']

# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0) 
# 0.2 mean our train is 80% and test 20%

In [19]:
#multiple linear regression
import statsmodels.api as sm
X_sm=X=sm.add_constant(X)
module=sm.OLS(y,X_sm)
module.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:          Average slary   R-squared:                       0.719
Model:                            OLS   Adj. R-squared:                  0.351
Method:                 Least Squares   F-statistic:                     1.956
Date:                Mon, 14 Dec 2020   Prob (F-statistic):             0.0156
Time:                        14:20:54   Log-Likelihood:                -360.01
No. Observations:                  91   AIC:                             824.0
Df Residuals:                      39   BIC:                             954.6
Df Model:                          51
Covariance Type:            nonrobust
====================================================================================================================
                                                       coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------------
const                                               78.1859     14.600      5.355      0.000      48.654     107.718
Rating                                               0.1546      4.123      0.037      0.970      -8.185       8.494
Size                                                 0.0009      0.001      0.650      0.520      -0.002       0.004
age                                                 -0.3831      0.180     -2.126      0.040      -0.748      -0.019
python                                              -3.8865      6.707     -0.579      0.566     -17.453       9.680
Industry_-1                                         -0.5834      5.481     -0.106      0.916     -11.670      10.503
Industry_Accounting                                 -8.2271      8.848     -0.930      0.358     -26.125       9.670
Industry_Advertising & Marketing                   -29.3188     19.654     -1.492      0.144     -69.073      10.436
Industry_Aerospace & Defense                         9.9352      6.264      1.586      0.121      -2.735      22.605
Industry_Architectural & Engineering Services       -5.8802     19.710     -0.298      0.767     -45.748      33.987
Industry_Auto Repair & Maintenance                  17.8161     10.243      1.739      0.090      -2.902      38.534
Industry_Automotive Parts & Accessories Stores      32.4089     17.903      1.810      0.078      -3.804      68.621
Industry_Banks & Credit Unions                     -25.3118     12.896     -1.963      0.057     -51.396       0.772
Industry_Biotech & Pharmaceuticals                  -7.5694      9.716     -0.779      0.441     -27.222      12.083
Industry_Chemical Manufacturing                      1.5164     19.573      0.077      0.939     -38.074      41.107
Industry_Computer Hardware & Software                9.1525     10.123      0.904      0.371     -11.324      29.629
Industry_Consulting                                  9.9064     18.976      0.522      0.605     -28.476      48.289
Industry_Consumer Products Manufacturing            -9.0762     13.959     -0.650      0.519     -37.310      19.158
Industry_Energy                                     15.6377     10.456      1.496      0.143      -5.512      36.787
Industry_Enterprise Software & Network Solutions    -1.3319     10.328     -0.129      0.898     -22.222      19.558
Industry_Express Delivery Services                  -9.0784     16.502     -0.550      0.585     -42.457      24.300
Industry_Financial Transaction Processing          -10.1074     17.552     -0.576      0.568     -45.610      25.395
Industry_Health Care Services & Hospitals           -3.2527      6.165     -0.528      0.601     -15.723       9.217
Industry_Health, Beauty, & Fitness                   9.0068     11.263      0.800      0.429     -13.775      31.789
Industry_IT Services                                -1.1359     10.327     -0.110      0.913     -22.024      19.752
Industry_Industrial Manufacturing                    2.0411     15.101      0.135      0.893     -28.504      32.586
Industry_Insurance Carriers                          7.5291      5.827      1.292      0.204      -4.257      19.315
Industry_Internet                                   -5.9955     13.161     -0.456      0.651     -32.616      20.624
Industry_Investment Banking & Asset Management       3.7768     13.004      0.290      0.773     -22.525      30.079
Industry_Lending                                    35.2225     12.871      2.737      0.009       9.188      61.257
Industry_Logistics & Supply Chain                   26.0785     18.062      1.444      0.157     -10.456      62.613
Industry_Mining                                     20.1882     14.325      1.409      0.167      -8.786      49.163
Industry_Other Retail Stores                       -39.4209     20.881     -1.888      0.066     -81.656       2.815
Industry_Staffing & Outsourcing                     11.4969     11.965      0.961      0.343     -12.704      35.698
Industry_Telecommunications Services                 8.5450      8.558      0.998      0.324      -8.766      25.856
Industry_Wholesale                                  14.2175     20.924      0.679      0.501     -28.106      56.540
Sector_-1                                           -0.5834      5.481     -0.106      0.916     -11.670      10.503
Sector_Accounting & Legal                           -8.2271      8.848     -0.930      0.358     -26.125       9.670
Sector_Aerospace & Defense                           9.9352      6.264      1.586      0.121      -2.735      22.605
Sector_Biotech & Pharmaceuticals                    -7.5694      9.716     -0.779      0.441     -27.222      12.083
Sector_Business Services                             0.4218      8.731      0.048      0.962     -17.239      18.082
Sector_Construction, Repair & Maintenance           17.8161     10.243      1.739      0.090      -2.902      38.534
Sector_Consumer Services                             9.0068     11.263      0.800      0.429     -13.775      31.789
Sector_Finance                                       3.5801      7.781      0.460      0.648     -12.158      19.318
Sector_Health Care                                  -3.2527      6.165     -0.528      0.601     -15.723       9.217
Sector_Information Technology                        0.6892      5.563      0.124      0.902     -10.563      11.941
Sector_Insurance                                     7.5291      5.827      1.292      0.204      -4.257      19.315
Sector_Manufacturing                                -5.5187      8.072     -0.684      0.498     -21.847      10.809
Sector_Mining & Metals                              20.1882     14.325      1.409      0.167      -8.786      49.163
Sector_Oil, Gas, Energy & Utilities                 15.6377     10.456      1.496      0.143      -5.512      36.787
Sector_Retail                                       -7.0121     11.478     -0.611      0.545     -30.228      16.204
Sector_Telecommunications                            8.5450      8.558      0.998      0.324      -8.766      25.856
Sector_Transportation & Logistics                   17.0001     10.766      1.579      0.122      -4.777      38.777
Revenue_$1 to $2 billion (USD)                       0.2213     14.504      0.015      0.988     -29.116      29.559
Revenue_$1 to $5 million (USD)                      26.8929     22.040      1.220      0.230     -17.687      71.473
Revenue_$10 to $25 million (USD)                    19.3330     24.258      0.797      0.430     -29.734      68.400
Revenue_$10+ billion (USD)                          -9.7291     19.127     -0.509      0.614     -48.417      28.959
Revenue_$100 to $500 million (USD)                   6.0828     11.391      0.534      0.596     -16.957      29.122
Revenue_$2 to $5 billion (USD)                      -7.0742     14.641     -0.483      0.632     -36.688      22.540
Revenue_$25 to $50 million (USD)                    11.1199     13.208      0.842      0.405     -15.596      37.836
Revenue_$5 to $10 billion (USD)                    -19.7312     25.518     -0.773      0.444     -71.347      31.885
Revenue_$5 to $10 million (USD)                     17.6553     27.675      0.638      0.527     -38.322      73.633
Revenue_$50 to $100 million (USD)                    8.6275     15.139      0.570      0.572     -21.995      39.250
Revenue_$500 million to $1 billion (USD)            16.0164     16.633      0.963      0.342     -17.627      49.660
Revenue_-1                                          12.6833      6.675      1.900      0.065      -0.818      26.185
Revenue_Less than $1 million (USD)                 -13.2667      7.640     -1.736      0.090     -28.720       2.187
Revenue_Unknown / Non-Applicable                     9.3547     10.762      0.869      0.390     -12.413      31.122
Type of ownership_-1                                12.6833      6.675      1.900      0.065      -0.818      26.185
Type of ownership_Company - Private                 13.5192      7.442      1.817      0.077      -1.534      28.572
Type of ownership_Company - Public                  22.5696     11.732      1.924      0.062      -1.160      46.299
Type of ownership_Contract                          -2.5262     35.503     -0.071      0.944     -74.337      69.285
Type of ownership_Hospital                         -12.5120     25.769     -0.486      0.630     -64.635      39.611
Type of ownership_Nonprofit Organization            18.2239     13.380      1.362      0.181      -8.839      45.287
Type of ownership_Subsidiary or Business Segment    26.2280     11.519      2.277      0.028       2.929      49.527
==============================================================================
Omnibus:                        2.042   Durbin-Watson:                   1.681
Prob(Omnibus):                  0.360   Jarque-Bera (JB):                1.559
Skew:                          -0.073   Prob(JB):                        0.459
Kurtosis:                       3.624   Cond. No.                     1.43e+17
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.52e-25. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [30]:
#linear regression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score # mtl train test sghiri btfrjini lperformence lal modele in reality
reg = LinearRegression().fit(X_train, y_train)
np.mean(cross_val_score(reg,X_train,y_train,scoring='neg_mean_absolute_error',cv=3))

-3583365402.228948

In [31]:
#losso
from sklearn.linear_model import LinearRegression, Lasso
# lasso regression 
lm_l = Lasso(alpha=.13)
lm_l.fit(X_train,y_train)
np.mean(cross_val_score(lm_l,X_train,y_train, scoring = 'neg_mean_absolute_error', cv= 3))

-20.45378545482717

In [36]:
# random forest 
from sklearn.ensemble import RandomForestRegressor
clf = RandomForestRegressor(max_depth=2, random_state=0)
clf.fit(X_train, y_train)

np.mean(cross_val_score(rf,X_train,y_train,scoring = 'neg_mean_absolute_error', cv= 3))

-17.95957385361552

In [41]:
# test ensembles 
tpred_lm = reg.predict(X_test)
tpred_lml = lm_l.predict(X_test)
tpred_rf = clf.predict(X_test)

from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(y_test,tpred_lm))
print(mean_absolute_error(y_test,tpred_lml))
print(mean_absolute_error(y_test,tpred_rf))

34.90084621407568
17.602472019365326
18.55676999191786